### ISSUE TITLE
分享下能测试的书源

### ISSUE THREAD

**Issue by jumuning** [gstory0404/fun_reader#1]

**Comment by jumuning** [comment]
测试打包apk 书架一直加载没有数据

**Comment by gstory0404** [comment]
[书源规则](https://github.com/gstory0404/fun_reader/blob/master/rule.md)

**Comment by jumuning** [comment]
根据你代码中有的规则去测试，一直请求不到数据

**Comment by gstory0404** [comment]
> 

最新的例子

**Comment by jumuning** [comment]
https://github.com/gstory0404/fun_reader/blob/master/file/spider.json 这个json 直接没法获取数据，一直加载

**Comment by gstory0404** [comment]
@jumuning 尝试其他书源

**Comment by jumuning** [comment]
不如直接发一个书源我测试下，可以我在去做其他书源

**Comment by gstory0404** [comment]
例子中dingdian书源 可以用 @jumuning
